### ISSUE TITLE
Implementation: `my_putnb`

### ISSUE THREAD

**Issue by SametSisartenep** [Garuda1/unixlib#13]
@Garuda1 , I just read your comment at #12 about a `my_putnb` function. How do you think it should be implemented?

Something like: `my_putnb(my_atoi("123456789")); => 123,456,789 OR 123.456.789 /* On some countries */`?

Also, we may want to add floating point support from `my_atof` or just to print hardcoded numbers, as in: `my_putnb(241423.141592); => 241,423.141592`.

**Comment by Garuda1** [comment]
I think the function should only do what it is supposed to do. As such, my_putnb would:

    ssize_t my_putnb(const int nb); /* Prints nb to stdout, returns nb of bytes written or FAILURE on error */

    my_putnb(42); /* Prints "42" */
    my_putnb(2147); /* Prints "2147" */
    my_putnb(-45); /* Prints "-45" */

Adding support for printing "," or "." depending on the localosation is indeed a nice feature, but it just makes the whole thing more complicated. Maybe such a feature could be implemented in `my_putnbf(const int nb)` (where the 'f' stands for "format"), and the delimiter character ("," or ".") could be `#define`d in `unixlib.h` as `MY_PUTNB_DELIM`.

However, if we want to work with floating point numbers, then we should probably start looking into `my_itoa` or `my_ftoa` to convert numbers to strings.

**Comment by Garuda1** [comment]
I'll start looking into implementing those:

- `char *my_itoa(const int nb, char *str)` (Prints `nb` as ASCII to `str` and returns `str`)
- `char *my_itoa_bin(const int nb, char *str)` (Same as `my_itoa` but prints in base 2)
- `char *my_itoa_hex(const int nb, char *str)` (Same as `my_itoa` but prints in base 16)

Now, those are nice, but I was thinking about passing the base as an argument. We would therefore only have one implementation, saving up lots of space in the compiled binaries:

- `char *my_itoa_base(const int nb, char *str, const char *base)`

Where:
- `nb` is the number to print
- `str` is the string where the number is printed (the function returns `str`)
- `base` is the base ("0123456789" or "01" or "jfsngjui4wuty", do as you want)

We would only have one implementation by doing so. The bases could be defined in `unixlib.h`:

    #define BASE_DEC "0123456789"
    #define BASE_BIN "01"
    #define BASE_HEX "0123456789abcdef"
    #define BASE_OCT "01234567"

Calling `my_itoa(42, my_string)` would simply be a macro defined as following:

    #define my_itoa(x, y) my_itoa_base(x, y, BASE_DEC)
