### ISSUE TITLE
my_exit not portable

### ISSUE THREAD

**Issue by Garuda1** [Garuda1/unixlib#6]
The `my_exit` function (`source/my_exit.c`) is not portable and only compiles on Linux x86 or Linux x86_64.

If anyone has enough knowledge of BSD/other UNIXes, then please add support for them :)

**Comment by chriscz** [comment]
could we not use `_exit` from `unistd.h` ? I have a PQ ready if you think so.

**Comment by Garuda1** [comment]
Well, it seems like it's a better idea, I mainly wanted to try out inline assembly so why not
